### ISSUE TITLE
Airline theme not recognized

### ISSUE THREAD

**Issue by sbmueller** [nightsense/stellarized#1]
I have installed `stellarized` using `Vundle`. When I try to set the airline theme using
```
let g:airline_theme='stellarized_light'
```
I get the following error when starting vim
```
Could not resolve airline theme "stellarized_light". Themes have been migrated to github.com/vim-airline/vim-airline-themes.
```
And airline is falling back to default theme. I have checked the airline theme is located in `~/.vim/bundle/stellarized/autoload/airline/themes`. Other themes in other folders seem to work. I don't know what's going wrong here, does anyone have an idea?

**Comment by sbmueller** [comment]
Just found out: it works when using `:AirlineTheme stellarized_light` from within vim. There seems to be trouble with the `.vimrc` statement.

**Comment by vn7n24fzkq** [comment]
Same error.
VIM Version : 
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48) 
Included patches: 1-1689
Extra patches: 8.0.0056            
SYSTEM : 
UBUNTU 16.04 LTS

**Comment by nightsense** [comment]
Thanks for reporting @sbmueller and @vn7n24fzkq , it should be fixed now (https://github.com/nightsense/stellarized/commit/79eb18dddd617bb762f999b702f4f9d9707cc8cf).

**Comment by vn7n24fzkq** [comment]
It's works now ! Thank you.

**Comment by sbmueller** [comment]
Confirmed, thank you @nightsense
