### ISSUE TITLE
Cursor randomly jumping

### ISSUE THREAD

**Issue by b-esc** [nightsense/stellarized#2]
using on neovim most recent,
os: debian 9
any file I open, the cursor jumps as if I bind % to hjkl once I leave a loop or function (in between braces {})

**Comment by nightsense** [comment]
Thanks @b-esc , should be fixed now (via [change in MatchParen highlight](https://github.com/nightsense/stellarized/commit/3dc71daea2db8695aed9c8afa41d6aa5418fac45#diff-37166afb2c7e911e838607d85f1ac912R44)).
