### ISSUE TITLE
Theme is not displaying correctly in Vim

### ISSUE THREAD

**Issue by jssee** [nightsense/stellarized#4]
For some reason, im having issues getting the theme to render correctly in vim, but the theme is just fine on Neovim, using an identical set up. The only difference is that in Neovim, im installing the color scheme via vim-plug, but for vanilla vim im using the native way, placing `stellarized.vim` into `.vim/colors`

Im using iTerm2, with tricolors, and vim8. here are some screenshots showing how the plain vim and nvim version differ.
<img width="591" alt="screen shot 2018-12-04 at 10 50 49 pm" src="https://user-images.githubusercontent.com/2642936/49489151-b5a18d80-f817-11e8-9c04-9ca0e447de4a.png">
<img width="547" alt="screen shot 2018-12-04 at 10 50 52 pm" src="https://user-images.githubusercontent.com/2642936/49489153-b803e780-f817-11e8-895a-cd70129efe18.png">

**Comment by jssee** [comment]
Update: I was able to fix the issue by updating vim, via homebrew,  from `8.0` -> `8.1`

the exact command I ran was `brew install vim --with-override-system-vi`

I think this should be mentioned in the readme, since most people probably think vim8 would work fine. 

awesome theme btw keep up the good work 😄

**Comment by nightsense** [comment]
Thanks @jssee! I've added a note, at least until I get a chance to investigate whether I can fix the theme to work with iTerm2+vim 8.0.
