### ISSUE TITLE
Better jsx/ts support

### ISSUE THREAD

**Issue by jssee** [nightsense/stellarized#5]
I really enjoy using this theme but would like to see it have a bit more robust support for certain filestypes. In my case, jsx and ts/tsx highlighting seem to be a bit minimal out of the box. 

I'd be more than happy to open a PR adding some support for these filetypes, I'm just not sure how to contribute to a theme that is built using `vim-colortemplate`, since they rely on unique files to generate the theme. or do you recommend just forking our own version? Thanks again for this wonderful theme

**Comment by nightsense** [comment]
Thanks @jssee, glad you like it! Thanks for the suggestion, but I personally feel that filetype-specific highlighting should be kept separate (in syntax plugins) from colorschemes, so I'd recommend either using a good syntax plugin for jsx and ts/tsx, or forking the theme if you really want it baked in.
